[package]
name = "gst-k4a"
version = "0.0.0-ohmyconanpleaseoverwriteme" # Overwritten during conan create.
authors = ["Andrej Orsula <andrej.orsula@aivero.com>", "Tobias Morell <tobias.morell@aivero.com>"]
license = "LGPL"
description = "GStreamer plugin containing `video/rgbd` source for an Azure Kinect DK (K4A) device"
keywords = [
    "Azure Kinect",
    "K4A",
    "Source",
    "GStreamer",
    "Rust",
]
repository = "https://gitlab.com/aivero/public/gstreamer/gst-k4a"
edition = "2018"
readme = "README.md"

[dependencies]
glib = "0.9"
gstreamer = "0.15"
gstreamer-base = "0.15"
gstreamer-video = "0.15"
lazy_static = "1.4"

[dependencies.gstreamer-depth-meta]
git = "https://gitlab.com/aivero/public/gstreamer/gst-depth-meta-rs"
tag = "1.2.0"

[dependencies.k4a]
git = "https://gitlab.com/aivero/public/k4a-rs"
tag = "0.4.5"

# Run `cargo fmt -- --check` and `cargo clippy -- -D warnings` before commits
[dev-dependencies.cargo-husky]
version = "1"
default-features = false # Disable features which are enabled by default
features = ["precommit-hook", "run-cargo-fmt", "run-cargo-clippy"]

[lib]
name = "gstk4asrc"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"
