[package]
name = "gstreamer-depth-meta"
version = "1.3.0"
authors = ["Niclas Moeslund Overby <noverby@prozum.dk>", "Tobias Morell <tobias.morell@aivero.com>", "Andrej Orsula <andrej.orsula@aivero.com>"]
description = "Rust bindings to gstreamer-depth-meta"
license = "Apache 2.0"
edition = "2018"

[dependencies]
glib-sys = "0.10"
glib = "0.10"
gstreamer-sys = "0.9"
gstreamer = "0.15"
gstreamer-video-sys = "0.9"
gstreamer-video = "0.15"
gstreamer-base = "0.15"
capnp = "0.12"

[build-dependencies]
pkg-config = "0.3"
capnpc = "0.12"

[dev-dependencies]
rand = "0.7"

# Run `cargo fmt -- --check` and `cargo clippy -- -D warnings` before commits
[dev-dependencies.cargo-husky]
version = "1"
default-features = false # Disable features which are enabled by default
features = ["precommit-hook", "run-cargo-fmt", "run-cargo-clippy"]
