[package]
name = "gst-realsense"
version = "0.0.0-ohmyconanpleaseoverwriteme"
authors = ["Niclas Moeslund Overby <niclas.overby@aivero.com>", "Andrej Orsula <andrej.orsula@aivero.com>", "Tobias Morell <tobias.morell@aivero.com>"]
license = "LGPL"
description = "GStreamer plugin containing `video/rgbd` source for a RealSense device"
keywords = ["Realsense", "Source", "GStreamer", "Rust"]
repository = "https://gitlab.com/aivero/public/gstreamer/gst-realsense"
edition = "2018"
readme = "README.md"
build = "build.rs"

[dependencies]
glib = "0.10"
gstreamer = "0.16"
gstreamer-base = "0.16"
gstreamer-video = "0.16"
lazy_static = "1.4"
capnp = "0.12"

[dependencies.gstreamer-depth-meta]
git = "https://gitlab.com/aivero/public/gstreamer/gst-depth-meta-rs"
tag = "1.3.0"

[dependencies.librealsense2]
git = "https://gitlab.com/aivero/public/librealsense-rs"
tag = "2.2.2"

[build-dependencies]
capnpc = "0.12"

# Run `cargo fmt -- --check` and `cargo clippy -- -D warnings` before commits
[dev-dependencies.cargo-husky]
version = "1"
default-features = false # Disable features which are enabled by default
features = ["precommit-hook", "run-cargo-fmt", "run-cargo-clippy"]

[lib]
name = "gstrealsensesrc"
crate-type = ["cdylib"]
path = "src/lib.rs"
